In [ ]:
import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

# ***1.About Dataset***

**New York City Airbnb Data Cleaning**

Airbnb, Inc is an American company that operates an online marketplace for lodging, primarily homestays for vacation rentals, and tourism activities. Based in San Francisco, California, the platform is accessible via website and mobile app. Airbnb does not own any of the listed properties; instead, it profits by receiving commission from each booking. The company was founded in 2008. Airbnb is a shortened version of its original name, AirBedandBreakfast.com.

**About Dataset**

***Context***

Since 2008, guests and hosts have used Airbnb to travel in a more unique, personalized way. As part of the Airbnb Inside initiative, this dataset describes the listing activity of homestays in New York City

**Content**

The following Airbnb activity is included in this New York dataset:

Listings, including full descriptions and average review score Reviews, including unique id for each reviewer and detailed comments Calendar, including listing id and the price and availability for that day

# ***2.Call Libraries***

In [ ]:

#  For data manipulations
import numpy as np
import pandas as pd
from numpy.random import default_rng
import missingno as msno
#  For plotting
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
#  For data Minor processing
from sklearn.preprocessing import StandardScaler



#  OS related
import os

# ***3. Read and Explore Dataset***

##**Read Dataset**

In [ ]:
df = pd.read_csv("Airbnb_Open_Data.csv");

<ipython-input-3-808823a4ee53>:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv");

###Overview Dataset

Display First Five rows of dataset

In [ ]:

df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

Display First last rows of dataset

In [ ]:
df.tail()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
60903,34638063,UNTITLED at Freeman - Bunk Bed Studio 501,17800277395,unconfirmed,Karen,Manhattan,Lower East Side,40.72217,-73.99141,United States,...,$51,2.0,7.0,12/19/2021,1.88,4.0,208.0,151.0,NaN,NaN
60904,34638615,"Spacious 1 bedroom with patio, roof, gym",32487265692,unconfirmed,Jay,Brooklyn,Williamsburg,40.71086,-73.95328,United States,...,$133,2.0,6.0,12/19/2021,1.12,5.0,1.0,358.0,NaN,NaN
60905,34639168,*Your Home Away From Home - Bedstuy*,61304939431,unconfirmed,Jerrell,Brooklyn,Bedford-Stuyvesant,40.69071,-73.93449,United States,...,$41,2.0,7.0,12/19/2021,1.41,2.0,2.0,317.0,NaN,NaN
60906,34639720,Shoreham Hotel - Modern Studio right in the he...,1331437153,unconfirmed,Shoreham,Manhattan,Midtown,40.76347,-73.97667,United States,...,$216,1.0,3.0,12/19/2021,0.67,3.0,44.0,348.0,NaN,NaN
60907,34640272,Shoreham Hotel - Chic Studio in an Unrivaled L...,17086930151,unconfirmed,Shoreham,Manhattan,Midtown,40.76205,-73.97731,United States,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN



*   Print the shape of data

In [ ]:
df.shape

(60908, 26)



* Print the name of all the columns

In [ ]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')



* Give the informaion of dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60908 entries, 0 to 60907
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              60908 non-null  int64
 1   NAME                            60705 non-null  object
 2   host id                         60908 non-null  int64
 3   host_identity_verified          60691 non-null  object
 4   host name                       60660 non-null  object
 5   neighbourhood group             60879 non-null  object
 6   neighbourhood                   60892 non-null  object
 7   lat                             60900 non-null  float64
 8   long                            60900 non-null  float64
 9   country                         60585 non-null  object
 10  country code                    60822 non-null  object
 11  instant_bookable                60822 non-null  object
 12  cancellation_policy             60851 non-null  object
 13  room type                       60908 non-null  object
 14  Construction year               60717 non-null  float64
 15  price                           60767 non-null  object
 16  service fee                     60767 non-null  object
 17  minimum nights                  60544 non-null  float64
 18  number of reviews               60756 non-null  float64
 19  last review                     50200 non-null  object
 20  reviews per month               50214 non-null  float64
 21  review rate number              60694 non-null  float64
 22  calculated host listings count  60763 non-null  float64
 23  availability 365                60475 non-null  float64
 24  house_rules                     32594 non-null  object
 25  license                         1 non-null      object
dtypes: float64(9), int64(2), object(15)
memory usage: 12.1+ MB



*   Print the Datatypes of the dataset

In [ ]:
df.dtypes

id                                  int64
NAME                               object
host id                             int64
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country code                       object
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                        object
license                            object
dtype: object

Obtaining the description of the dataframe

In [ ]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,6.090800e+04,6.090800e+04,60900.000000,60900.000000,60717.000000,60544.000000,60756.000000,50214.000000,60694.000000,60763.000000,60475.000000
mean,1.782080e+07,4.932868e+10,40.728084,-73.949620,2012.490587,7.391946,28.060109,1.510616,3.299832,7.979148,155.051988
std,9.710964e+06,2.852081e+10,0.055656,0.049694,5.767205,35.803717,52.567890,1.868100,1.272863,33.293035,134.233450
min,1.001254e+06,1.303496e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,9.411070e+06,2.467164e+10,40.688700,-73.982940,2007.000000,1.000000,1.000000,0.260000,2.000000,1.000000,21.000000
50%,1.782080e+07,4.916695e+10,40.722352,-73.954610,2012.000000,2.000000,7.000000,0.930000,3.000000,1.000000,130.000000
75%,2.623054e+07,7.410530e+10,40.762760,-73.932060,2018.000000,5.000000,29.000000,2.230000,4.000000,2.000000,282.000000
max,3.464027e+07,9.876313e+10,40.916850,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,426.000000

In [ ]:
df.isnull().sum()

id                                    0
NAME                                203
host id                               0
host_identity_verified              217
host name                           248
neighbourhood group                  29
neighbourhood                        16
lat                                   8
long                                  8
country                             323
country code                         86
instant_bookable                     86
cancellation_policy                  57
room type                             0
Construction year                   191
price                               141
service fee                         141
minimum nights                      364
number of reviews                   152
last review                       10708
reviews per month                 10694
review rate number                  214
calculated host listings count      145
availability 365                    433
house_rules                       28314
license                           60907
dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.nunique()

id                                60908
NAME                              56318
host id                           60907
host_identity_verified                2
host name                         12632
neighbourhood group                   7
neighbourhood                       224
lat                               21042
long                              16833
country                               1
country code                          1
instant_bookable                      2
cancellation_policy                   3
room type                             5
Construction year                    20
price                              1151
service fee                         231
minimum nights                      140
number of reviews                   470
last review                        1837
reviews per month                  1015
review rate number                    5
calculated host listings count       78
availability 365                    437
house_rules                        1976
license                               1
dtype: int64

# ***4.Data Cleaning***

Remove the Duplicates if any

In [ ]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [ ]:
print(list(df.columns))

['id', 'NAME', 'host id', 'host_identity_verified', 'host name', 'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country', 'country code', 'instant_bookable', 'cancellation_policy', 'room type', 'Construction year', 'price', 'service fee', 'minimum nights', 'number of reviews', 'last review', 'reviews per month', 'review rate number', 'calculated host listings count', 'availability 365', 'house_rules', 'license']

Let's rename some columns, remove spaces

In [ ]:
new_col_names = {
                  'host id'                 : 'Host Id',
                  'host name'               : 'Host Name',
                 'neighbourhood group'      : 'Neighbourhood group' ,
                  'country code'            :  'Country code',
                  'room type'               :  'Room type',
                  'Construction year'       : 'Construction year',
                  'service fee'             : 'Service fee',
                  'number of reviews'       :  'Number of reviews' ,
                  'last review'             :  'Last review',
                  'reviews per month'       : 'Reviews per month',
                  'review rate number'      :  'Review rate number',
          'calculated host listings count'  :'Calculated host listings count',
                  'availability 365'        :  'Availability 365'     ,
                  'id': 'ID',
                  'NAME': 'Name',
                  'host_identity_verified' : 'Host Identity Verified',
                  'neighbourhood':'Neighbourhood' ,
                  'lat': 'Lat',
                  'long': 'Long',
                  'country': 'Country',
                  'country code': 'Country Code',
                  'instant_bookable': 'Instant Bookable',
                  'cancellation_policy': 'Cancellation Policy',
                  'price': 'Price',
                  'minimum nights': 'Minimum Nights',
                  'house_rules': 'House Rules',
                  'license' : 'License'


}

In [ ]:
new_col_names

{'host id': 'Host Id',
 'host name': 'Host Name',
 'neighbourhood group': 'Neighbourhood group',
 'country code': 'Country Code',
 'room type': 'Room type',
 'Construction year': 'Construction year',
 'service fee': 'Service fee',
 'number of reviews': 'Number of reviews',
 'last review': 'Last review',
 'reviews per month': 'Reviews per month',
 'review rate number': 'Review rate number',
 'calculated host listings count': 'Calculated host listings count',
 'availability 365': 'Availability 365',
 'id': 'ID',
 'NAME': 'Name',
 'host_identity_verified': 'Host Identity Verified',
 'neighbourhood': 'Neighbourhood',
 'lat': 'Lat',
 'long': 'Long',
 'country': 'Country',
 'instant_bookable': 'Instant Bookable',
 'cancellation_policy': 'Cancellation Policy',
 'price': 'Price',
 'minimum nights': 'Minimum Nights',
 'house_rules': 'House Rules',
 'license': 'License'}

Rename the columns

In [ ]:
df.rename(
         columns = new_col_names,
         inplace = True,
         )

See the column Names are changed....

In [ ]:
df.columns

Index(['ID', 'Name', 'Host Id', 'Host Identity Verified', 'Host Name',
       'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country Code', 'Instant Bookable', 'Cancellation Policy', 'Room type',
       'Construction year', 'Price', 'Service fee', 'Minimum Nights',
       'Number of reviews', 'Last review', 'Reviews per month',
       'Review rate number', 'Calculated host listings count',
       'Availability 365', 'House Rules', 'License'],
      dtype='object')

In [ ]:
#check renaming

df.head()
df.columns.values

array(['ID', 'Name', 'Host Id', 'Host Identity Verified', 'Host Name',
       'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country Code', 'Instant Bookable', 'Cancellation Policy',
       'Room type', 'Construction year', 'Price', 'Service fee',
       'Minimum Nights', 'Number of reviews', 'Last review',
       'Reviews per month', 'Review rate number',
       'Calculated host listings count', 'Availability 365',
       'House Rules', 'License'], dtype=object)

Count the missing values of every column in terms of % and show the result

---

In [ ]:
# calculate the % missing values
percentage_result = df.isnull().sum()/df.shape[0] * 100
# create a DataFrame to show case the result
percentage_result = pd.DataFrame({"columns": percentage_result.keys(), "% missing": percentage_result})
percentage_result.reset_index(drop=True, inplace=True)
percentage_result

                           columns  % missing
0                               ID   0.000000
1                             Name   0.333290
2                          Host Id   0.000000
3           Host Identity Verified   0.356275
4                        Host Name   0.407171
5              Neighbourhood group   0.047613
6                    Neighbourhood   0.026269
7                              Lat   0.013135
8                             Long   0.013135
9                          Country   0.530308
10                    Country Code   0.141197
11                Instant Bookable   0.141197
12             Cancellation Policy   0.093584
13                       Room type   0.000000
14               Construction year   0.313588
15                           Price   0.231497
16                     Service fee   0.231497
17                  Minimum Nights   0.597623
18               Number of reviews   0.249557
19                     Last review  17.580613
20               Reviews per month  17.557628
21              Review rate number   0.351350
22  Calculated host listings count   0.238064
23                Availability 365   0.710908
24                     House Rules  46.486504
25                         License  99.998358

**id and host_id columns:**

In [ ]:
df["ID"].unique().shape[0]/df["ID"].shape[0]*100
#print("\n-----\n")
#df["host_id"].unique().shape[0]/df["host_id"].shape[0]*100

100.0

 Most of these values ​​are distinct for each line. I don't think it makes sense for analysis, so I'll delete them.

---

In [ ]:
df.drop(columns=["Country Code"],axis=1,inplace=True);
df

,ID,Name,Host Id,Host Identity Verified,Host Name,Neighbourhood group,Neighbourhood,Lat,Long,Instant Bookable,...,Construction year,Price,Service fee,Minimum Nights,Number of reviews,Last review,Reviews per month,Review rate number,Calculated host listings count,Availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,...,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,...,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,True,...,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,True,...,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,...,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60903,34638063,UNTITLED at Freeman - Bunk Bed Studio 501,17800277395,unconfirmed,Karen,Manhattan,Lower East Side,40.72217,-73.99141,True,...,2017.0,$257,$51,2.0,7.0,12/19/2021,1.88,4.0,208.0,151.0
60904,34638615,"Spacious 1 bedroom with patio, roof, gym",32487265692,unconfirmed,Jay,Brooklyn,Williamsburg,40.71086,-73.95328,False,...,2004.0,$664,$133,2.0,6.0,12/19/2021,1.12,5.0,1.0,358.0
60905,34639168,*Your Home Away From Home - Bedstuy*,61304939431,unconfirmed,Jerrell,Brooklyn,Bedford-Stuyvesant,40.69071,-73.93449,False,...,2020.0,$204,$41,2.0,7.0,12/19/2021,1.41,2.0,2.0,317.0
60906,34639720,Shoreham Hotel - Modern Studio right in the he...,1331437153,unconfirmed,Shoreham,Manhattan,Midtown,40.76347,-73.97667,False,...,2013.0,"$1,079",$216,1.0,3.0,12/19/2021,0.67,3.0,44.0,348.0
60907,34640272,Shoreham Hotel - Chic Studio in an Unrivaled L...,17086930151,unconfirmed,Shoreham,Manhattan,Midtown,40.76205,-73.97731,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**price and service_fee columns:**

 Convert from object type to float64: remove the $ sign and unwanted characters

from the records.

---

In [ ]:
def remove_dollar_sign(value):
    if pd.isna(value):
        return np.NaN
    else:
        return float(value.replace("$","").replace(",","").replace(" ",""))

In [ ]:
df["Price"]=df["Price"].apply(lambda x: remove_dollar_sign(x))
df["Price"]

0         966.0
1         142.0
2         620.0
3         368.0
4         204.0
          ...
60903     257.0
60904     664.0
60905     204.0
60906    1079.0
60907       NaN
Name: Price, Length: 60908, dtype: float64

In [ ]:
df["Service fee"]=df["Service fee"].apply(lambda x: remove_dollar_sign(x))
df["Service fee"]

0        193.0
1         28.0
2        124.0
3         74.0
4         41.0
         ...
60903     51.0
60904    133.0
60905     41.0
60906    216.0
60907      NaN
Name: Service fee, Length: 60908, dtype: float64

Changing "last review" to pandas datetime

In [ ]:
df["Last review"]=pd.to_datetime(df["Last review"])

***Data after processing***

In [ ]:
df.head()

,ID,Name,Host Id,Host Identity Verified,Host Name,Neighbourhood group,Neighbourhood,Lat,Long,Instant Bookable,...,Construction year,Price,Service fee,Minimum Nights,Number of reviews,Last review,Reviews per month,Review rate number,Calculated host listings count,Availability 365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,False,...,2020.0,966.0,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,False,...,2007.0,142.0,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,True,...,2005.0,620.0,124.0,3.0,0.0,NaT,NaN,5.0,1.0,352.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,True,...,2005.0,368.0,74.0,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,False,...,2009.0,204.0,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0

In [ ]:
df.shape
print("\n-----\n")
df.dtypes

-----

ID                                         int64
Name                                      object
Host Id                                    int64
Host Identity Verified                    object
Host Name                                 object
Neighbourhood group                       object
Neighbourhood                             object
Lat                                      float64
Long                                     float64
Instant Bookable                          object
Cancellation Policy                       object
Room type                                 object
Construction year                        float64
Price                                    float64
Service fee                              float64
Minimum Nights                           float64
Number of reviews                        float64
Last review                       datetime64[ns]
Reviews per month                        float64
Review rate number                       float64
Calculated host listings count           float64
Availability 365                         float64
dtype: object

In [ ]:
df.isnull().sum()

ID                                    0
Name                                203
Host Id                               0
Host Identity Verified              217
Host Name                           248
Neighbourhood group                  29
Neighbourhood                        16
Lat                                   8
Long                                  8
Instant Bookable                     86
Cancellation Policy                  57
Room type                             0
Construction year                   191
Price                               141
Service fee                         141
Minimum Nights                      364
Number of reviews                   152
Last review                       10708
Reviews per month                 10694
Review rate number                  214
Calculated host listings count      145
Availability 365                    433
dtype: int64

In [ ]:

df.nunique()

ID                                60908
Name                              56318
Host Id                           60907
Host Identity Verified                2
Host Name                         12632
Neighbourhood group                   7
Neighbourhood                       224
Lat                               21042
Long                              16833
Instant Bookable                      2
Cancellation Policy                   3
Room type                             5
Construction year                    20
Price                              1151
Service fee                         231
Minimum Nights                      140
Number of reviews                   470
Last review                        1837
Reviews per month                  1015
Review rate number                    5
Calculated host listings count       78
Availability 365                    437
dtype: int64

In [ ]:
df.dropna(subset=['Availability 365'], inplace=True)
print(len(df))

48577

In [ ]:
df.to_csv('Airbnb_Cleaned.csv')